const allProductsData = {
    allProductsData: [
      {
        id: 1,
        discount: 10,
        img: "/assets/flash-deals/flash-1.jpg",
        name: "กางเกงยีนส์เอวสูง",
        price: 144,
        desc: "ขนาดฟรีไซส์ เอว 24-30 สะโพก 33-38ความยาว 40",
      },
      {
        id: 2,
        discount: 20,
        img: "/assets/flash-deals/flash-2.png",
        name: "กระเป๋าผ้าโบว์สุดคิ้ว",
        price: 104,
        desc: " กระเป๋าผ้าประดับโบว์สีชมพู ขนาด 44x43. จุของได้เยอะมาก",
      },
      {
        id: 3,
        discount: 40,
        img: "/assets/flash-deals/flash-3.png",
        name: "เสื้อเชิ้ตสีชมพู",
        price: 168,
        desc: "เสื้อเชิ้ตสีชมพูออ่อน ขนาดพอดีตัว ไซส์ s-m ใส่ได้ อก 42 ยาว 25",
      },
      {
        id: 4,
        discount: 10,
        img: "/assets/flash-deals/flash-4.png",
        name: "เบบี้ทรี สีขาวลายดิสโก้",
        price: 216,
        desc: "เบบรี้ สีขาวลายดิสโก้ ทรงรัดรูปผ้านิ่มยืดใส่สบาย อก32-36 ยาว 16",
      }, 
      {
        id: 5,
        discount: 50,
        img: "/assets/flash-deals/flash-5.png",
        name: "เสื้อกล้ามลายดอก",
        price: 75,
        desc: "เสื้อกล้ามลายดอกไม้สีฟ้าขอบลูกไม้ อก 32-36 ยาว 15",
      },
      {
        id: 6,
        discount: 30,
        img: "/assets/flash-deals/flash-6.png",
        name: "เสื้อเชิ้ตหนังสีน้ำตาล",
        price: 245,
        desc: "เสื้อเชิ้ตหนังสีน้ำตาล มีกระเป๋าด้านซ้าย1ข้าง มีซิปรูด ผ้าหนังกำมะหยี่",
      },
      {
        id: 7,
        discount: 10,
        img: "/assets/flash-deals/flash-7.png",
        name: "รองเท้าเมรี่เจนสีแดง",
        price: 160,
        desc: "รองเท้าเมรี่เจนสีแดง หนังเคลือบเงา มีส้น ไซส์38",
      },
      {
        id: 8,
        discount: 10,
        img: "/assets/flash-deals/flash-8.png",
        name: "กระเป๋าสะพายโบว์",
        price: 140,
        desc: "กระเป๋าสะพายโบว์ สีขาว สะพายข้างสะพายไหล่ จุของได้เยอะ",
      },
      {
        id: 9,
        img: "/assets/allproduct/all-1.png",
        name: "เสื้อกล้ามสีดำ",
        price: 160,
        desc: "เสื้อกล้ามสีดำ ขอบขาว อก 34-38 ยาว 18 ",
      },
      {
        id: 10,
        img: "/assets/allproduct/all-2.png",
        name: "กระเป๋าหนังสีดำ",
        price: 230,
        desc: "กระเป๋าหนังสีดำ (เฉพาะกระเป๋าไม่รวมตุ๊กตา) มี3 ช่องใส่ของ จุของได้เยอะมาก",
      },
      {
        id: 11,
        img: "/assets/allproduct/all-3.png",
        name: "หมวกยีนส์แต่งลูกไม้",
        price: 170,
        desc: "หมวกสียีนส์แต่งขอบลูกไม้ ประดับลูกปัดโบว์ตรงกลาง ปรับขนาดได้",
      },
      {
        id: 12,
        img: "/assets/allproduct/all-4.png",
        name: "สร้อยลูกปัดจี้โบว์",
        price: 60,
        desc: "สร้อยลูกปัดเงินผสมลูกปัดมุกขาว จี้โบว์ **ไม่แนะนำให้ใส่อาบน้ำ สินค้าอาจจะลอกหรือดำได้**",
      },
      {
        id: 13,
        img: "/assets/allproduct/all-5.png",
        name: "กระเป้าผ้าลูกฟูก",
        price: 110,
        desc: "กระเป๋าผ้าลูกฟูกลายเชอรรี่ สีขาว ขนาด 40x38",
      },
      {
        id: 14,
        img: "/assets/allproduct/all-6.png",
        name: "เสื้อสเวตเตอร์คอซิป",
        price: 330,
        desc: "เสื้อสเวตเตอรืคอซิป สีเทามีโลโก้ด้านซ้าย อก 42-46 ยาว 28",
      },
      {
        id: 15,
        img: "/assets/allproduct/all-7.png",
        name: "แหวนรูปหัวใจ",
        price: 40,
        desc: "แหวนรูปหัวใจ สีทองแดง เรียบหรูดูแพง ปรับขนาดได้",
      },
      {
        id: 16,
        img: "/assets/allproduct/all-8.png",
        name: "กำไลเชือกถัก",
        price: 30,
        desc: "กำไลเชือกถัก เชือกสีดำร้อยลูกปัด สีใส สีเทา สีดำ จี้ดาวใส",
      },
      {
        id: 17,
        img: "/assets/allproduct/all-9.png",
        name: "เสื้อแขนตุ๊กตา",
        price: 140,
        desc: "เสื้อเเขนตุ๊กตาสีขาวครีม ลายดอกไม้ อก 36-40",
      },
      {
        id: 18,
        img: "/assets/allproduct/all-10.png",
        name: "กระโปรงลายดอกไม้",
        price: 210,
        desc: "กระโปรงลายดอกไม้ สีขาวครีม ผ้าลูกไม้2ชั้น เอว 23-30 มีเชือกผูกเอวยืดได้",
      },

       {
        id: 19,
        img: "/assets/allproduct/all-11.png",
        name: "กระโปรงยีนส์2เลเยอร์",
        price: 190,
        desc: "กระโปรงยีนส์2เลเยอร์ ทรงบานออก มีสม็อคด้านหลังยืดได้ตามขนาดเอว เอว 24-30 ยาว 15",
      }, {
        id: 20,
        img: "/assets/allproduct/all-12.png",
        name: "กางเกงขาสั้นจีบหน้า",
        price: 180,
        desc: "กางเกงขาสั้นจีบหน้า สีครีม ลุคโอมันนี่ เอว 25 ยาว 17 รอบขา 23",
      },
      {
        id: 21,
        img: "/assets/allproduct/all-13.png",
        name: "เสื้อยืดโอเวอร์ไซส์",
        price: 200,
        desc: "เสื้อยืดโอเวอร์ไซต์สีเทาดำ ลายตัวอักษร ฟรีไซส์ อก48 ยาว 30",
      },
      {
        id: 22,
        img: "/assets/allproduct/all-14.png",
        name: "กางเกงขาสั้นสามส่วน",
        price: 170,
        desc: "กางเกงขาสั้นสามส่วน สีดำ เอว 28 ยาว 22",
      },
      {
        id: 23,
        img: "/assets/allproduct/all-15.png",
        name: "เสื้อยืดทูโทน",
        price: 160,
        desc: "เสื้อยืดทูโทน แขนสีดำ ตัวเสื้อสีเทา กึ่งโอเวอร์ไซต์ อก 42 ยาว 26",
      },

       {
        id: 24,
        img: "/assets/allproduct/all-16.png",
        name: "เซ็ตต่างหูเงิน",
        price: 30,
        desc: "เซ็ตต่างหูเงิน 4 ชิ้น **ไม่แนะนำให้ใส่อาบน้ำ สินค้าอาจลอกหรือดำได้**",
      }, {
        id: 25,
        img: "/assets/allproduct/all-17.png",
        name: "กางเกงยีนส์สีเฟด",
        price: 220,
        desc: "กางเกงยีนส์สีดำเฟด กระบอกใหญ่ เอวสูง เอว 26 ยาว 40",
      },
      {
        id: 26,
        img: "/assets/allproduct/all-18.png",
        name: "หมวกบันนี่ไหมพรม",
        price: 180,
        desc: "หมวกบันนี่ไหมพรมลายตาราง สีขาวฟ้า",
      },
      {
        id: 27,
        img: "/assets/allproduct/all-19.png",
        name: "สร้อยเชือกถัก",
        price: 79,
        desc: "สร้อยเชือกถักประดับหินสีชมพู จี้หัวใจ",
      },
      {
        id: 28,
        img: "/assets/allproduct/all-20.png",
        name: "กำไลเงินจี้เพชร",
        price: 80,
        desc: "กำไลเงินจี้เพชร ฝั่งนึงเป็นเลสเส้นเล็ก อีกฝั่งเป็นโซ่2เส้น 1เส้น2สไตล์ ปรับขนาดได้",
      },
      {
        id: 29,
        img: "/assets/allproduct/all-21.png",
        name: "เสื้อสายเดี่ยว",
        price: 145,
        desc: "เสื้อสายเดี่ยวสม็อคเอว สีแดง อก32-38 ยาว 16",
      },
      {
        id: 30,
        img: "/assets/allproduct/all-22.png",
        name: "เสื้อสายเดี่ยวแหวกกลาง",
        price: 150,
        desc: "เสื้อสายเดี่ยวแหวกกลาง สีกากี อก 32-36 ยาว 18",
      }, {
        id: 31,
        img: "/assets/allproduct/all-23.png",
        name: "กระโปรงยีนส์",
        price: 190,
        desc: "กระโปรงยีนส์เบสิค สียีนส์เข้ม เอวสม็อคด้านหลัง เอว24-28 ยาว 16",
      },
      {
        id: 32,
        img: "/assets/allproduct/all-24.png",
        name: "เสื้อโอเวอร์ไซส์สีพื้น",
        price: 130,
        desc: "เสื้อโอเวอร์ไซต์สีพื้น สีเหลืองครีม อก 44 ยาว 28",
      },
      {
        id: 33,
        img: "/assets/allproduct/all-25.png",
        name: "เสื้อเชิ้ตลายสก็อต",
        price: 160,
        desc: "เสื้อเชิ้ตลายสก็อต สีน้ำตาล โอเวอร์ไซส์ อก 44 ยาว 30",
      },
      {
        id: 34,
        img: "/assets/allproduct/all-26.png",
        name: "รองเท้าเมรี่เจน",
        price: 235,
        desc: "รองเท้าเมรี่เจน สีดำ ทรงนักเรียนญี่ปุ่น ไซส์ 38",
      },
      {
        id: 35,
        img: "/assets/allproduct/all-27.png",
        name: "รองเท้าแตะหัวโต",
        price: 130,
        desc: "รองเท้าแตะหัวโต สีขาว (ไม่รวมของตกแต่ง เฉพาะรองเท้าเท่านั้น)",
      },
      {
        id: 36,
        img: "/assets/allproduct/all-28.png",
        name: "กำไลข้อมือเงิน",
        price: 55,
        desc: "กำไลข้อมือเงิน 2เส้น จี้หัวใจ **ไม่แนะนำให้ใส่อาบน้ำ สินค้าอาจดำหรือลอกได้**",
      },
      {
        id: 37,
        img: "/assets/allproduct/all-29.png",
        name: "กำไลเงินผีเสื้อ",
        price: 49,
        desc: "กำไลเงินจี้ผีเสื้อ ปรับขนาดได้ **ไม่แนะนำให้ใส่อาบน้ำ สินค้าอาจดำหรือลอกได้**",
      },
      {
        id: 38,
        img: "/assets/allproduct/all-30.png",
        name: "รองเท้าผ้าใบ",
        price: 245,
        desc: "รองเท้าผ้าใบ สีขาวฟ้า พื้นสูง 5cm. ไซส์ 38",
      },{
        id: 39,
        discount: 20,
        img: "/assets/allproduct/all-31.png",
        name: "สายเดี่ยวสม็อค",
        price: 144,
        desc: "สายเดี่ยวสม็อค สายเป็นแบบผูก ปรับได้ตามต้องการ อก36-40 ยาว 22",
      },
      {
        id: 40,
        discount: 10,
        img: "/assets/allproduct/all-32.png",
        name: "กระเป๋าผ้าลายดอก",
        price: 108,
        desc: "กระเป๋าผ้าลายดอก สีเขียว ผ้านุ่มจุของได้เยอะ",
      },
      {
        id: 41,
        discount: 30,
        img: "/assets/allproduct/all-33.png",
        name: "กระโปงยาวลายสก็อต",
        price: 154,
        desc: "กระโปรงยาวลายสก็อต สีฟ้าแต่งขอบ เอวยืดได้ตามขนาด เอว 24-30 ยาว 28",
      },
      {
        id: 42,
        discount: 10,
        img: "/assets/allproduct/all-34.png",
        name: "หมวกแก็ปลายการ์ตูน",
        price: 135,
        desc: "หมวกแก็ปลายการ์ตูน สีขาว น่ารักๆ ปรับขนาดด้านหลังได้",
      },
      {
        id: 43,
        discount: 10,
        img: "/assets/allproduct/all-35.png",
        name: "สร้อคอมุก",
        price: 72,
        desc: "สร้อยคอมุก 2ชั้น สีขาว จี้มุกแบนกลม",
      },
      {
        id: 44,
        discount: 10,
        img: "/assets/allproduct/all-36.png",
        name: "เซ็ตกำไลลูกปัด",
        price: 36,
        desc: "เซ็ตกำไลลูกปัด 2ชิ้น โทนขาวฟ้า ลูกปัดใสผสมมุก",
      },
      {
        id: 45,
        discount: 20,
        img: "/assets/allproduct/all-37.png",
        name: "กางเกงยีนส์อ่อนสามส่วน",
        price: 168,
        desc: "กางเกงยีนส์อ่อนสามส่วน เอว 26 ยาว 22",
      },
      {
        id: 46,
        discount: 10,
        img: "/assets/allproduct/all-38.png",
        name: "เดรสลูกไม้ยาว",
        price: 180,
        desc: "เดรสลูกไม้ยาว สีครีม ขอบลูกไม้ แขนสายเดี่ยว อก 32-38 ยาว 28",
      },
      {
        id: 47,
        discount: 30,
        img: "/assets/allproduct/all-39.png",
        name: "รองเท้าส้นเตี้ย",
        price: 119,
        desc: "รองเท้าส้นเตี้ย ติดแกรมสีเงิน สวยมินิมอล ไซส์ 38",
      },
      {
        id: 48,
        img: "/assets/allproduct/all-40.png",
        name: "กระเป๋าถือลูกไม้",
        price: 120,
        desc: "กระเป๋าถือลูกไม้ ไม่บางมาก ประดับขอบสีแดงมีโบว์ให้ผูก",
      },
    ],
  };
  
  export default allProductsData;
  